# Generated by Django 3.2.18 on 2023-06-29 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20230629_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director_department', to='department.employee'),
        ),
    ]
